package inliner

import "testing"

// The applyRtlMapping cases of shadcn transform-rtl.test.ts, verbatim.
func TestApplyRtlMappingUpstreamCases(t *testing.T) {
	for _, tc := range [][2]string{
		{"ml-2", "ms-2"},
		{"mr-4", "me-4"},
		{"-ml-2", "-ms-2"},
		{"-mr-4", "-me-4"},
		{"pl-2", "ps-2"},
		{"pr-4", "pe-4"},
		{"left-0", "start-0"},
		{"right-0", "end-0"},
		{"right-1", "end-1"},
		{"-left-2", "-start-2"},
		{"-right-2", "-end-2"},
		{"inset-l-0", "inset-inline-start-0"},
		{"inset-r-0", "inset-inline-end-0"},
		{"border-l", "border-s"},
		{"border-r", "border-e"},
		{"border-l-2", "border-s-2"},
		{"border-r-2", "border-e-2"},
		{"rounded-l-md", "rounded-s-md"},
		{"rounded-r-md", "rounded-e-md"},
		{"rounded-tl-md", "rounded-ss-md"},
		{"rounded-tr-md", "rounded-se-md"},
		{"rounded-bl-md", "rounded-es-md"},
		{"rounded-br-md", "rounded-ee-md"},
		{"text-left", "text-start"},
		{"text-right", "text-end"},
		{"scroll-ml-2", "scroll-ms-2"},
		{"scroll-mr-2", "scroll-me-2"},
		{"scroll-pl-2", "scroll-ps-2"},
		{"scroll-pr-2", "scroll-pe-2"},
		{"float-left", "float-start"},
		{"float-right", "float-end"},
		{"clear-left", "clear-start"},
		{"clear-right", "clear-end"},
		{"origin-left", "origin-start"},
		{"origin-right", "origin-end"},
		{"origin-top-left", "origin-top-start"},
		{"origin-top-right", "origin-top-end"},
		{"origin-bottom-left", "origin-bottom-start"},
		{"origin-bottom-right", "origin-bottom-end"},
		{"hover:ml-2", "hover:ms-2"},
		{"focus:pl-4", "focus:ps-4"},
		{"sm:md:ml-2", "sm:md:ms-2"},
		{"sm:group-data-[size=default]/alert-dialog-content:text-left", "sm:group-data-[size=default]/alert-dialog-content:text-start"},
		{"ml-[10px]", "ms-[10px]"},
		{"left-[50%]", "start-[50%]"},
		{"ml-2/50", "ms-2/50"},
		{"ml-2 mr-4 pl-2 pr-4", "ms-2 me-4 ps-2 pe-4"},
		{"data-[side=inline-start]:slide-in-from-right-2", "data-[side=inline-start]:slide-in-from-end-2"},
		{"data-[side=inline-start]:slide-out-to-right-2", "data-[side=inline-start]:slide-out-to-end-2"},
		{"data-[side=inline-end]:slide-in-from-left-2", "data-[side=inline-end]:slide-in-from-start-2"},
		{"data-[side=inline-end]:slide-out-to-left-2", "data-[side=inline-end]:slide-out-to-start-2"},
		{"data-[side=left]:slide-in-from-right-2", "data-[side=left]:slide-in-from-right-2"},
		{"data-[side=right]:slide-in-from-left-2", "data-[side=right]:slide-in-from-left-2"},
		{"bg-red-500", "bg-red-500"},
		{"flex", "flex"},
		{"mx-auto", "mx-auto"},
		{"px-4", "px-4"},
		{"border-ring", "border-ring"},
		{"border-ring/50", "border-ring/50"},
		{"border-lime-500", "border-lime-500"},
		{"text-left", "text-start"},
		{"text-right", "text-end"},
		{"float-left", "float-start"},
		{"origin-left", "origin-start"},
		{"origin-top-left", "origin-top-start"},
		{"scroll-m-4", "scroll-m-4"},
		{"-translate-x-1/2", "-translate-x-1/2 rtl:translate-x-1/2"},
		{"translate-x-full", "translate-x-full rtl:-translate-x-full"},
		{"-translate-x-px", "-translate-x-px rtl:translate-x-px"},
		{"after:-translate-x-1/2", "after:-translate-x-1/2 rtl:after:translate-x-1/2"},
		{"group-hover:translate-x-2", "group-hover:translate-x-2 rtl:group-hover:-translate-x-2"},
		{"-translate-y-1/2", "-translate-y-1/2"},
		{"translate-y-full", "translate-y-full"},
		{"space-x-4", "space-x-4 rtl:space-x-reverse"},
		{"space-x-2", "space-x-2 rtl:space-x-reverse"},
		{"space-x-0", "space-x-0 rtl:space-x-reverse"},
		{"divide-x-2", "divide-x-2 rtl:divide-x-reverse"},
		{"divide-x-0", "divide-x-0 rtl:divide-x-reverse"},
		{"md:space-x-4", "md:space-x-4 rtl:md:space-x-reverse"},
		{"hover:divide-x-2", "hover:divide-x-2 rtl:hover:divide-x-reverse"},
		{"space-y-4", "space-y-4"},
		{"divide-y-2", "divide-y-2"},
		{"cursor-w-resize", "cursor-w-resize rtl:cursor-e-resize"},
		{"cursor-e-resize", "cursor-e-resize rtl:cursor-w-resize"},
		{"hover:cursor-w-resize", "hover:cursor-w-resize rtl:hover:cursor-e-resize"},
		{"cn-rtl-flip size-4", "rtl:rotate-180 size-4"},
		{"size-4 cn-rtl-flip", "size-4 rtl:rotate-180"},
		{"cn-rtl-flip", "rtl:rotate-180"},
		{"cn-rtl-flip ml-2", "rtl:rotate-180 ms-2"},
		{"data-[side=left]:top-1", "data-[side=left]:top-1"},
		{"data-[side=left]:-right-1", "data-[side=left]:-right-1"},
		{"data-[side=right]:-left-1", "data-[side=right]:-left-1"},
		{"data-[side=left]:right-0", "data-[side=left]:right-0"},
		{"data-[side=right]:left-0", "data-[side=right]:left-0"},
		{"data-[side=left]:ml-2", "data-[side=left]:ms-2"},
		{"data-[side=right]:pl-4", "data-[side=right]:ps-4"},
		{"data-[side=left]:text-left", "data-[side=left]:text-start"},
		{"rtl:ml-2", "rtl:ml-2"},
		{"rtl:text-right", "rtl:text-right"},
		{"rtl:space-x-reverse", "rtl:space-x-reverse"},
		{"ltr:ml-2", "ltr:ml-2"},
		{"ltr:text-left", "ltr:text-left"},
		{"ml-2 rtl:mr-2", "ms-2 rtl:mr-2"},
		{"ltr:pl-4 pr-4", "ltr:pl-4 pe-4"},
		{"text-left rtl:text-right ltr:text-left", "text-start rtl:text-right ltr:text-left"},
		{"ltr:-translate-x-1/2 rtl:-translate-x-1/2", "ltr:-translate-x-1/2 rtl:-translate-x-1/2"},
	} {
		if got := applyRtlMapping(tc[0]); got != tc[1] {
			t.Errorf("applyRtlMapping(%q) = %q, want %q", tc[0], got, tc[1])
		}
	}
}
