// Package all registers every example in examples.Registry. Import it
// for its side effect where the registry is rendered (cmd/docs, tests).
package all

import (
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/axadrn/shadcn-templ/v2/internal/ui/examples"

	exaccordion "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/accordion"
	exalert "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/alert"
	exalertdialog "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/alertdialog"
	exaspectratio "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/aspectratio"
	exattachment "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/attachment"
	exavatar "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/avatar"
	exbadge "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/badge"
	exbreadcrumb "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/breadcrumb"
	exbubble "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/bubble"
	exbutton "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/button"
	exbuttongroup "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/buttongroup"
	excalendar "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/calendar"
	excard "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/card"
	excarousel "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/carousel"
	exchart "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/chart"
	excheckbox "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/checkbox"
	excollapsible "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/collapsible"
	excombobox "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/combobox"
	excommand "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/command"
	excontextmenu "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/contextmenu"
	exdatatable "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/datatable"
	exdatepicker "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/datepicker"
	exdialog "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/dialog"
	exdrawer "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/drawer"
	exdropdownmenu "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/dropdownmenu"
	exempty "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/empty"
	exfield "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/field"
	exhovercard "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/hovercard"
	exicon "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/icon"
	exinput "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/input"
	exinputgroup "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/inputgroup"
	exinputotp "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/inputotp"
	exitem "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/item"
	exkbd "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/kbd"
	exlabel "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/label"
	exmarker "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/marker"
	exmenubar "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/menubar"
	exmessage "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/message"
	exmessagescroller "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/messagescroller"
	exnativeselect "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/nativeselect"
	exnavigationmenu "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/navigationmenu"
	expagination "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/pagination"
	expopover "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/popover"
	exprogress "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/progress"
	exquestionnaire "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/questionnaire"
	exradiogroup "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/radiogroup"
	exresizable "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/resizable"
	exscrollarea "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/scrollarea"
	exscrollfade "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/scrollfade"
	exselectex "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/selectex"
	exseparator "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/separator"
	exsheet "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/sheet"
	exshimmer "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/shimmer"
	exsidebar "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/sidebar"
	exskeleton "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/skeleton"
	exslider "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/slider"
	exspinner "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/spinner"
	exswitchex "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/switchex"
	extable "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/table"
	extabs "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/tabs"
	extextarea "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/textarea"
	extoast "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/toast"
	extoggle "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/toggle"
	extogglegroup "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/togglegroup"
	extooltip "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/tooltip"
	extypography "github.com/axadrn/shadcn-templ/v2/internal/ui/examples/typography"
)

func init() {
	for name, entry := range entries {
		examples.Registry[name] = entry
	}
}

// lazy renders an example through its constructor, called on render: a
// function value keeps the constructors' template bodies out of this
// package (a call would inline every one of them into init, recompiling all
// examples on every edit).
func lazy(newComponent func() templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		return newComponent().Render(ctx, w)
	})
}

var entries = map[string]examples.RegistryEntry{
	"toast-demo":                        {Component: lazy(extoast.ToastDemo), File: "toast/toast_demo.templ"},
	"toast-types":                       {Component: lazy(extoast.ToastTypes), File: "toast/toast_types.templ"},
	"toast-promise":                     {Component: lazy(extoast.ToastPromise), File: "toast/toast_promise.templ"},
	"tabs-demo":                         {Component: lazy(extabs.TabsDemo), File: "tabs/tabs_demo.templ"},
	"tabs-line":                         {Component: lazy(extabs.TabsLine), File: "tabs/tabs_line.templ"},
	"tabs-vertical":                     {Component: lazy(extabs.TabsVertical), File: "tabs/tabs_vertical.templ"},
	"tabs-icons":                        {Component: lazy(extabs.TabsIcons), File: "tabs/tabs_icons.templ"},
	"tabs-disabled":                     {Component: lazy(extabs.TabsDisabled), File: "tabs/tabs_disabled.templ"},
	"table-demo":                        {Component: lazy(extable.TableDemo), File: "table/table_demo.templ"},
	"table-footer":                      {Component: lazy(extable.TableFooterExample), File: "table/table_footer.templ"},
	"table-actions":                     {Component: lazy(extable.TableActions), File: "table/table_actions.templ"},
	"toggle-demo":                       {Component: lazy(extoggle.ToggleDemo), File: "toggle/toggle_demo.templ"},
	"toggle-outline":                    {Component: lazy(extoggle.ToggleOutline), File: "toggle/toggle_outline.templ"},
	"toggle-text":                       {Component: lazy(extoggle.ToggleText), File: "toggle/toggle_text.templ"},
	"toggle-sizes":                      {Component: lazy(extoggle.ToggleSizes), File: "toggle/toggle_sizes.templ"},
	"toggle-disabled":                   {Component: lazy(extoggle.ToggleDisabled), File: "toggle/toggle_disabled.templ"},
	"toggle-group-demo":                 {Component: lazy(extogglegroup.ToggleGroupDemo), File: "togglegroup/togglegroup_demo.templ"},
	"toggle-group-outline":              {Component: lazy(extogglegroup.ToggleGroupOutline), File: "togglegroup/togglegroup_outline.templ"},
	"toggle-group-sizes":                {Component: lazy(extogglegroup.ToggleGroupSize), File: "togglegroup/togglegroup_size.templ"},
	"toggle-group-spacing":              {Component: lazy(extogglegroup.ToggleGroupSpacing), File: "togglegroup/togglegroup_spacing.templ"},
	"toggle-group-vertical":             {Component: lazy(extogglegroup.ToggleGroupVertical), File: "togglegroup/togglegroup_vertical.templ"},
	"toggle-group-disabled":             {Component: lazy(extogglegroup.ToggleGroupDisabled), File: "togglegroup/togglegroup_disabled.templ"},
	"toggle-group-font-weight-selector": {Component: lazy(extogglegroup.ToggleGroupCustom), File: "togglegroup/togglegroup_custom.templ"},
	"tooltip-demo":                      {Component: lazy(extooltip.TooltipDemo), File: "tooltip/tooltip_demo.templ"},
	"tooltip-sides":                     {Component: lazy(extooltip.TooltipSides), File: "tooltip/tooltip_sides.templ"},
	"tooltip-keyboard":                  {Component: lazy(extooltip.TooltipKeyboard), File: "tooltip/tooltip_keyboard.templ"},
	"tooltip-disabled":                  {Component: lazy(extooltip.TooltipDisabled), File: "tooltip/tooltip_disabled.templ"},
	"chart-demo":                        {Component: lazy(exchart.ChartDemo), File: "chart/chart_demo.templ"},
	"chart-example":                     {Component: lazy(exchart.ChartExample), File: "chart/chart_example.templ"},
	"chart-example-grid":                {Component: lazy(exchart.ChartExampleGrid), File: "chart/chart_example.templ"},
	"chart-example-axis":                {Component: lazy(exchart.ChartExampleAxis), File: "chart/chart_example.templ"},
	"chart-example-tooltip":             {Component: lazy(exchart.ChartExampleTooltip), File: "chart/chart_example.templ"},
	"chart-example-legend":              {Component: lazy(exchart.ChartExampleLegend), File: "chart/chart_example.templ"},
	"chart-tooltip":                     {Component: lazy(exchart.ChartTooltipExample), File: "chart/chart_tooltip.templ"},
	"skeleton-demo":                     {Component: lazy(exskeleton.SkeletonDemo), File: "skeleton/skeleton_demo.templ"},
	"skeleton-avatar":                   {Component: lazy(exskeleton.SkeletonAvatar), File: "skeleton/skeleton_avatar.templ"},
	"skeleton-card":                     {Component: lazy(exskeleton.SkeletonCard), File: "skeleton/skeleton_card.templ"},
	"skeleton-text":                     {Component: lazy(exskeleton.SkeletonText), File: "skeleton/skeleton_text.templ"},
	"skeleton-form":                     {Component: lazy(exskeleton.SkeletonForm), File: "skeleton/skeleton_form.templ"},
	"skeleton-table":                    {Component: lazy(exskeleton.SkeletonTable), File: "skeleton/skeleton_table.templ"},
	"spinner-demo":                      {Component: lazy(exspinner.SpinnerDemo), File: "spinner/spinner_demo.templ"},
	"spinner-custom":                    {Component: lazy(exspinner.SpinnerCustom), File: "spinner/spinner_custom.templ"},
	"spinner-size":                      {Component: lazy(exspinner.SpinnerSize), File: "spinner/spinner_size.templ"},
	"spinner-button":                    {Component: lazy(exspinner.SpinnerButton), File: "spinner/spinner_button.templ"},
	"spinner-badge":                     {Component: lazy(exspinner.SpinnerBadge), File: "spinner/spinner_badge.templ"},
	"spinner-input-group":               {Component: lazy(exspinner.SpinnerInputGroup), File: "spinner/spinner_input_group.templ"},
	"spinner-empty":                     {Component: lazy(exspinner.SpinnerEmpty), File: "spinner/spinner_empty.templ"},
	"textarea-demo":                     {Component: lazy(extextarea.TextareaDemo), File: "textarea/textarea_demo.templ"},
	"textarea-field":                    {Component: lazy(extextarea.TextareaField), File: "textarea/textarea_field.templ"},
	"textarea-disabled":                 {Component: lazy(extextarea.TextareaDisabled), File: "textarea/textarea_disabled.templ"},
	"textarea-invalid":                  {Component: lazy(extextarea.TextareaInvalid), File: "textarea/textarea_invalid.templ"},
	"textarea-button":                   {Component: lazy(extextarea.TextareaButton), File: "textarea/textarea_button.templ"},
	"sidebar-demo":                      {Component: lazy(exsidebar.SidebarDemo), File: "sidebar/sidebar_demo.templ"},
	"sheet-demo":                        {Component: lazy(exsheet.SheetDemo), File: "sheet/sheet_demo.templ"},
	"sheet-side":                        {Component: lazy(exsheet.SheetSide), File: "sheet/sheet_side.templ"},
	"sheet-no-close-button":             {Component: lazy(exsheet.SheetNoCloseButton), File: "sheet/sheet_no_close_button.templ"},
	"select-demo":                       {Component: lazy(exselectex.SelectDemo), File: "selectex/select_demo.templ"},
	"select-align-item":                 {Component: lazy(exselectex.SelectAlignItem), File: "selectex/select_align_item.templ"},
	"select-groups":                     {Component: lazy(exselectex.SelectGroupsExample), File: "selectex/select_groups.templ"},
	"select-scrollable":                 {Component: lazy(exselectex.SelectScrollable), File: "selectex/select_scrollable.templ"},
	"select-disabled":                   {Component: lazy(exselectex.SelectDisabled), File: "selectex/select_disabled.templ"},
	"select-invalid":                    {Component: lazy(exselectex.SelectInvalid), File: "selectex/select_invalid.templ"},
	"radio-group-demo":                  {Component: lazy(exradiogroup.RadioGroupDemo), File: "radiogroup/radio_group_demo.templ"},
	"radio-group-description":           {Component: lazy(exradiogroup.RadioGroupDescription), File: "radiogroup/radio_group_description.templ"},
	"radio-group-choice-card":           {Component: lazy(exradiogroup.RadioGroupChoiceCard), File: "radiogroup/radio_group_choice_card.templ"},
	"radio-group-fieldset":              {Component: lazy(exradiogroup.RadioGroupFieldset), File: "radiogroup/radio_group_fieldset.templ"},
	"radio-group-disabled":              {Component: lazy(exradiogroup.RadioGroupDisabled), File: "radiogroup/radio_group_disabled.templ"},
	"radio-group-invalid":               {Component: lazy(exradiogroup.RadioGroupInvalid), File: "radiogroup/radio_group_invalid.templ"},
	"resizable-demo":                    {Component: lazy(exresizable.ResizableDemo), File: "resizable/resizable_demo.templ"},
	"resizable-vertical":                {Component: lazy(exresizable.ResizableVertical), File: "resizable/resizable_vertical.templ"},
	"resizable-handle":                  {Component: lazy(exresizable.ResizableHandle), File: "resizable/resizable_handle.templ"},
	"resizable-rtl":                     {Component: lazy(exresizable.ResizableRTL), File: "resizable/resizable_rtl.templ"},
	"popover-demo":                      {Component: lazy(expopover.PopoverDemo), File: "popover/popover_demo.templ"},
	"popover-basic":                     {Component: lazy(expopover.PopoverBasic), File: "popover/popover_basic.templ"},
	"popover-alignments":                {Component: lazy(expopover.PopoverAlignments), File: "popover/popover_alignments.templ"},
	"popover-form":                      {Component: lazy(expopover.PopoverForm), File: "popover/popover_form.templ"},
	"pagination-demo":                   {Component: lazy(expagination.PaginationDemo), File: "pagination/pagination_demo.templ"},
	"pagination-simple":                 {Component: lazy(expagination.PaginationSimple), File: "pagination/pagination_simple.templ"},
	"pagination-icons-only":             {Component: lazy(expagination.PaginationIconsOnly), File: "pagination/pagination_icons_only.templ"},
	"progress-demo":                     {Component: lazy(exprogress.ProgressDemo), File: "progress/progress_demo.templ"},
	"progress-label":                    {Component: lazy(exprogress.ProgressWithLabel), File: "progress/progress_label.templ"},
	"progress-controlled":               {Component: lazy(exprogress.ProgressControlled), File: "progress/progress_controlled.templ"},
	"scroll-area-demo":                  {Component: lazy(exscrollarea.ScrollAreaDemo), File: "scrollarea/scroll_area_demo.templ"},
	"scroll-area-horizontal-demo":       {Component: lazy(exscrollarea.ScrollAreaHorizontalDemo), File: "scrollarea/scroll_area_horizontal_demo.templ"},
	"scroll-area-example":               {Component: lazy(exscrollarea.ScrollAreaExample), File: "scrollarea/scroll_area_example.templ"},
	"menubar-checkbox":                  {Component: lazy(exmenubar.MenubarCheckbox), File: "menubar/menubar_checkbox.templ"},
	"menubar-demo":                      {Component: lazy(exmenubar.MenubarDemo), File: "menubar/menubar_demo.templ"},
	"menubar-example":                   {Component: lazy(exmenubar.MenubarExample), File: "menubar/menubar_example.templ"},
	"menubar-icons":                     {Component: lazy(exmenubar.MenubarIcons), File: "menubar/menubar_icons.templ"},
	"menubar-radio":                     {Component: lazy(exmenubar.MenubarRadio), File: "menubar/menubar_radio.templ"},
	"menubar-submenu":                   {Component: lazy(exmenubar.MenubarSubmenu), File: "menubar/menubar_submenu.templ"},
	"message-actions":                   {Component: lazy(exmessage.MessageActions), File: "message/message_actions.templ", Style: "base-rhea"},
	"message-attachment":                {Component: lazy(exmessage.MessageAttachment), File: "message/message_attachment.templ", Style: "base-rhea"},
	"message-avatar":                    {Component: lazy(exmessage.MessageAvatar), File: "message/message_avatar.templ", Style: "base-rhea"},
	"message-demo":                      {Component: lazy(exmessage.MessageDemo), File: "message/message_demo.templ", Style: "base-rhea"},
	"message-example":                   {Component: lazy(exmessage.MessageExample), File: "message/message_example.templ"},
	"message-group":                     {Component: lazy(exmessage.MessageGroup), File: "message/message_group.templ", Style: "base-rhea"},
	"message-header-footer":             {Component: lazy(exmessage.MessageHeaderFooter), File: "message/message_header_footer.templ", Style: "base-rhea"},
	"message-markdown":                  {Component: lazy(exmessage.MessageMarkdownDemo), File: "message/message_markdown.templ", Style: "base-rhea"},
	"message-scroller-anchoring":        {Component: lazy(exmessagescroller.MessageScrollerAnchoring), File: "messagescroller/messagescroller_anchoring.templ", Style: "base-rhea"},
	"message-scroller-animation":        {Component: lazy(exmessagescroller.MessageScrollerAnimation), File: "messagescroller/messagescroller_animation.templ", Style: "base-rhea"},
	"message-scroller-commands":         {Component: lazy(exmessagescroller.MessageScrollerCommands), File: "messagescroller/messagescroller_commands.templ", Style: "base-rhea"},
	"message-scroller-demo":             {Component: lazy(exmessagescroller.MessageScrollerDemo), File: "messagescroller/messagescroller_demo.templ", Style: "base-rhea"},
	"message-scroller-group-chat":       {Component: lazy(exmessagescroller.MessageScrollerGroupChat), File: "messagescroller/messagescroller_group_chat.templ", Style: "base-rhea"},
	"message-scroller-load-history":     {Component: lazy(exmessagescroller.MessageScrollerLoadHistory), File: "messagescroller/messagescroller_load_history.templ", Style: "base-rhea"},
	"message-scroller-opening-position": {Component: lazy(exmessagescroller.MessageScrollerOpeningPosition), File: "messagescroller/messagescroller_opening_position.templ", Style: "base-rhea"},
	"message-scroller-previous-context": {Component: lazy(exmessagescroller.MessageScrollerPreviousContext), File: "messagescroller/messagescroller_previous_context.templ", Style: "base-rhea"},
	"message-scroller-scrollable":       {Component: lazy(exmessagescroller.MessageScrollerScrollable), File: "messagescroller/messagescroller_scrollable.templ", Style: "base-rhea"},
	"message-scroller-state":            {Component: lazy(exmessagescroller.MessageScrollerState), File: "messagescroller/messagescroller_state.templ", Style: "base-rhea"},
	"message-scroller-streaming":        {Component: lazy(exmessagescroller.MessageScrollerStreaming), File: "messagescroller/messagescroller_streaming.templ", Style: "base-rhea"},
	"message-scroller-visibility":       {Component: lazy(exmessagescroller.MessageScrollerVisibility), File: "messagescroller/messagescroller_visibility.templ", Style: "base-rhea"},
	"message-scroller-example":          {Component: lazy(exmessagescroller.MessageScrollerExample), File: "messagescroller/messagescroller_example.templ"},
	"native-select-demo":                {Component: lazy(exnativeselect.NativeSelectDemo), File: "nativeselect/native_select_demo.templ"},
	"native-select-disabled":            {Component: lazy(exnativeselect.NativeSelectDisabled), File: "nativeselect/native_select_disabled.templ"},
	"native-select-groups":              {Component: lazy(exnativeselect.NativeSelectGroups), File: "nativeselect/native_select_groups.templ"},
	"native-select-invalid":             {Component: lazy(exnativeselect.NativeSelectInvalid), File: "nativeselect/native_select_invalid.templ"},
	"native-select-example":             {Component: lazy(exnativeselect.NativeSelectExample), File: "nativeselect/native_select_example.templ"},
	"attachment-demo":                   {Component: lazy(exattachment.AttachmentDemo), File: "attachment/attachment_demo.templ", Style: "base-rhea"},
	"attachment-example":                {Component: lazy(exattachment.AttachmentExample), File: "attachment/attachment_example.templ"},
	"attachment-group":                  {Component: lazy(exattachment.AttachmentGroup), File: "attachment/attachment_group.templ", Style: "base-rhea"},
	"attachment-image":                  {Component: lazy(exattachment.AttachmentImage), File: "attachment/attachment_image.templ", Style: "base-rhea"},
	"attachment-sizes":                  {Component: lazy(exattachment.AttachmentSizes), File: "attachment/attachment_sizes.templ", Style: "base-rhea"},
	"attachment-states":                 {Component: lazy(exattachment.AttachmentStates), File: "attachment/attachment_states.templ", Style: "base-rhea"},
	"attachment-trigger":                {Component: lazy(exattachment.AttachmentTrigger), File: "attachment/attachment_trigger.templ", Style: "base-rhea"},
	"marker-border":                     {Component: lazy(exmarker.MarkerBorderDemo), File: "marker/marker_border.templ", Style: "base-rhea"},
	"marker-demo":                       {Component: lazy(exmarker.MarkerDemo), File: "marker/marker_demo.templ", Style: "base-rhea"},
	"marker-icon":                       {Component: lazy(exmarker.MarkerIconDemo), File: "marker/marker_icon.templ", Style: "base-rhea"},
	"marker-link-button":                {Component: lazy(exmarker.MarkerLinkButtonDemo), File: "marker/marker_link_button.templ", Style: "base-rhea"},
	"marker-separator":                  {Component: lazy(exmarker.MarkerSeparatorDemo), File: "marker/marker_separator.templ", Style: "base-rhea"},
	"marker-shimmer":                    {Component: lazy(exmarker.MarkerShimmerDemo), File: "marker/marker_shimmer.templ", Style: "base-rhea"},
	"shimmer-demo":                      {Component: lazy(exshimmer.ShimmerDemo), File: "shimmer/shimmer_demo.templ"},
	"shimmer-angle":                     {Component: lazy(exshimmer.ShimmerAngle), File: "shimmer/shimmer_angle.templ"},
	"shimmer-color":                     {Component: lazy(exshimmer.ShimmerColor), File: "shimmer/shimmer_color.templ"},
	"shimmer-duration":                  {Component: lazy(exshimmer.ShimmerDuration), File: "shimmer/shimmer_duration.templ"},
	"shimmer-marker":                    {Component: lazy(exshimmer.ShimmerMarker), File: "shimmer/shimmer_marker.templ", Style: "base-rhea"},
	"shimmer-none":                      {Component: lazy(exshimmer.ShimmerNone), File: "shimmer/shimmer_none.templ"},
	"shimmer-once":                      {Component: lazy(exshimmer.ShimmerOnce), File: "shimmer/shimmer_once.templ", Style: "base-rhea"},
	"shimmer-spread":                    {Component: lazy(exshimmer.ShimmerSpread), File: "shimmer/shimmer_spread.templ"},
	"scroll-fade-demo":                  {Component: lazy(exscrollfade.ScrollFadeDemo), File: "scrollfade/scroll_fade_demo.templ"},
	"scroll-fade-edge":                  {Component: lazy(exscrollfade.ScrollFadeEdge), File: "scrollfade/scroll_fade_edge.templ"},
	"scroll-fade-horizontal":            {Component: lazy(exscrollfade.ScrollFadeHorizontal), File: "scrollfade/scroll_fade_horizontal.templ"},
	"scroll-fade-none":                  {Component: lazy(exscrollfade.ScrollFadeNone), File: "scrollfade/scroll_fade_none.templ"},
	"scroll-fade-overflow":              {Component: lazy(exscrollfade.ScrollFadeOverflow), File: "scrollfade/scroll_fade_overflow.templ"},
	"scroll-fade-size":                  {Component: lazy(exscrollfade.ScrollFadeSize), File: "scrollfade/scroll_fade_size.templ"},
	"marker-status":                     {Component: lazy(exmarker.MarkerStatusDemo), File: "marker/marker_status.templ", Style: "base-rhea"},
	"marker-variants":                   {Component: lazy(exmarker.MarkerVariantsDemo), File: "marker/marker_variants.templ", Style: "base-rhea"},
	"marker-example":                    {Component: lazy(exmarker.MarkerExample), File: "marker/marker_example.templ"},
	"bubble-alignment":                  {Component: lazy(exbubble.BubbleAlignmentDemo), File: "bubble/bubble_alignment.templ", Style: "base-rhea"},
	"bubble-collapsible":                {Component: lazy(exbubble.BubbleCollapsible), File: "bubble/bubble_collapsible.templ", Style: "base-rhea"},
	"bubble-demo":                       {Component: lazy(exbubble.BubbleDemo), File: "bubble/bubble_demo.templ", Style: "base-rhea"},
	"bubble-group-demo":                 {Component: lazy(exbubble.BubbleGroupDemo), File: "bubble/bubble_group_demo.templ", Style: "base-rhea"},
	"bubble-link-button":                {Component: lazy(exbubble.BubbleLinkButtonDemo), File: "bubble/bubble_link_button.templ", Style: "base-rhea"},
	"bubble-markdown":                   {Component: lazy(exbubble.BubbleMarkdownDemo), File: "bubble/bubble_markdown.templ", Style: "base-rhea"},
	"bubble-popover":                    {Component: lazy(exbubble.BubblePopoverDemo), File: "bubble/bubble_popover.templ", Style: "base-rhea"},
	"bubble-reactions":                  {Component: lazy(exbubble.BubbleReactionsDemo), File: "bubble/bubble_reactions.templ", Style: "base-rhea"},
	"bubble-tooltip":                    {Component: lazy(exbubble.BubbleTooltipDemo), File: "bubble/bubble_tooltip.templ", Style: "base-rhea"},
	"bubble-variants":                   {Component: lazy(exbubble.BubbleVariantsDemo), File: "bubble/bubble_variants.templ", Style: "base-rhea"},
	"bubble-example":                    {Component: lazy(exbubble.BubbleExample), File: "bubble/bubble_example.templ"},
	"separator-demo":                    {Component: lazy(exseparator.SeparatorDemo), File: "separator/separator_demo.templ"},
	"separator-vertical":                {Component: lazy(exseparator.SeparatorVertical), File: "separator/separator_vertical.templ"},
	"separator-menu":                    {Component: lazy(exseparator.SeparatorMenu), File: "separator/separator_menu.templ"},
	"separator-list":                    {Component: lazy(exseparator.SeparatorList), File: "separator/separator_list.templ"},
	"label-demo":                        {Component: lazy(exlabel.LabelDemo), File: "label/label_demo.templ"},
	"kbd-demo":                          {Component: lazy(exkbd.KbdDemo), File: "kbd/kbd_demo.templ"},
	"kbd-group":                         {Component: lazy(exkbd.KbdGroupExample), File: "kbd/kbd_group.templ"},
	"kbd-button":                        {Component: lazy(exkbd.KbdButton), File: "kbd/kbd_button.templ"},
	"kbd-tooltip":                       {Component: lazy(exkbd.KbdTooltip), File: "kbd/kbd_tooltip.templ"},
	"kbd-input-group":                   {Component: lazy(exkbd.KbdInputGroup), File: "kbd/kbd_input_group.templ"},
	"item-demo":                         {Component: lazy(exitem.ItemDemo), File: "item/item_demo.templ"},
	"item-variant":                      {Component: lazy(exitem.ItemVariant), File: "item/item_variant.templ"},
	"item-size":                         {Component: lazy(exitem.ItemSizeDemo), File: "item/item_size.templ"},
	"item-icon":                         {Component: lazy(exitem.ItemIcon), File: "item/item_icon.templ"},
	"item-avatar":                       {Component: lazy(exitem.ItemAvatar), File: "item/item_avatar.templ"},
	"item-image":                        {Component: lazy(exitem.ItemImage), File: "item/item_image.templ"},
	"item-group":                        {Component: lazy(exitem.ItemGroupExample), File: "item/item_group.templ"},
	"item-header":                       {Component: lazy(exitem.ItemHeaderDemo), File: "item/item_header.templ"},
	"item-link":                         {Component: lazy(exitem.ItemLink), File: "item/item_link.templ"},
	"item-dropdown":                     {Component: lazy(exitem.ItemDropdown), File: "item/item_dropdown.templ"},
	"input-otp-demo":                    {Component: lazy(exinputotp.InputOTPDemo), File: "inputotp/input_otp_demo.templ"},
	"input-otp-pattern":                 {Component: lazy(exinputotp.InputOTPPattern), File: "inputotp/input_otp_pattern.templ"},
	"input-otp-separator":               {Component: lazy(exinputotp.InputOTPSeparatorExample), File: "inputotp/input_otp_separator.templ"},
	"input-otp-disabled":                {Component: lazy(exinputotp.InputOTPDisabled), File: "inputotp/input_otp_disabled.templ"},
	"input-otp-controlled":              {Component: lazy(exinputotp.InputOTPControlled), File: "inputotp/input_otp_controlled.templ"},
	"input-otp-invalid":                 {Component: lazy(exinputotp.InputOTPInvalid), File: "inputotp/input_otp_invalid.templ"},
	"input-otp-four-digits":             {Component: lazy(exinputotp.InputOTPFourDigits), File: "inputotp/input_otp_four_digits.templ"},
	"input-otp-alphanumeric":            {Component: lazy(exinputotp.InputOTPAlphanumeric), File: "inputotp/input_otp_alphanumeric.templ"},
	"input-otp-form":                    {Component: lazy(exinputotp.InputOTPForm), File: "inputotp/input_otp_form.templ"},
	"input-group-demo":                  {Component: lazy(exinputgroup.InputGroupDemo), File: "inputgroup/inputgroup_demo.templ"},
	"input-group-inline-start":          {Component: lazy(exinputgroup.InputGroupInlineStart), File: "inputgroup/inputgroup_inline_start.templ"},
	"input-group-inline-end":            {Component: lazy(exinputgroup.InputGroupInlineEnd), File: "inputgroup/inputgroup_inline_end.templ"},
	"input-group-block-start":           {Component: lazy(exinputgroup.InputGroupBlockStart), File: "inputgroup/inputgroup_block_start.templ"},
	"input-group-block-end":             {Component: lazy(exinputgroup.InputGroupBlockEnd), File: "inputgroup/inputgroup_block_end.templ"},
	"input-group-icon":                  {Component: lazy(exinputgroup.InputGroupIcon), File: "inputgroup/inputgroup_icon.templ"},
	"input-group-text":                  {Component: lazy(exinputgroup.InputGroupText), File: "inputgroup/inputgroup_text.templ"},
	"input-group-button":                {Component: lazy(exinputgroup.InputGroupButton), File: "inputgroup/inputgroup_button.templ"},
	"input-group-kbd":                   {Component: lazy(exinputgroup.InputGroupKbd), File: "inputgroup/inputgroup_kbd.templ"},
	"input-group-dropdown":              {Component: lazy(exinputgroup.InputGroupDropdown), File: "inputgroup/inputgroup_dropdown.templ"},
	"input-group-spinner":               {Component: lazy(exinputgroup.InputGroupSpinner), File: "inputgroup/inputgroup_spinner.templ"},
	"input-group-textarea":              {Component: lazy(exinputgroup.InputGroupTextareaExample), File: "inputgroup/inputgroup_textarea.templ"},
	"input-group-custom":                {Component: lazy(exinputgroup.InputGroupCustom), File: "inputgroup/inputgroup_custom.templ"},
	"input-group-basic":                 {Component: lazy(exinputgroup.InputGroupBasic), File: "inputgroup/input_group_basic.templ"},
	"input-group-button-group":          {Component: lazy(exinputgroup.InputGroupButtonGroup), File: "inputgroup/input_group_button_group.templ"},
	"input-group-in-card":               {Component: lazy(exinputgroup.InputGroupInCard), File: "inputgroup/input_group_in_card.templ"},
	"input-group-label":                 {Component: lazy(exinputgroup.InputGroupLabel), File: "inputgroup/input_group_label.templ"},
	"input-group-textarea-examples":     {Component: lazy(exinputgroup.InputGroupTextareaExamples), File: "inputgroup/input_group_textarea_examples.templ"},
	"input-group-tooltip":               {Component: lazy(exinputgroup.InputGroupTooltip), File: "inputgroup/input_group_tooltip.templ"},
	"input-group-with-addons":           {Component: lazy(exinputgroup.InputGroupWithAddons), File: "inputgroup/input_group_with_addons.templ"},
	"input-group-with-buttons":          {Component: lazy(exinputgroup.InputGroupWithButtons), File: "inputgroup/input_group_with_buttons.templ"},
	"input-group-with-kbd":              {Component: lazy(exinputgroup.InputGroupWithKbd), File: "inputgroup/input_group_with_kbd.templ"},
	"input-group-with-tooltip":          {Component: lazy(exinputgroup.InputGroupWithTooltip), File: "inputgroup/input_group_with_tooltip.templ"},
	"muted-item-group":                  {Component: lazy(exitem.MutedItemGroup), File: "item/muted_item_group.templ"},
	"outline-item-group":                {Component: lazy(exitem.OutlineItemGroup), File: "item/outline_item_group.templ"},
	"empty-card":                        {Component: lazy(exempty.EmptyInCard), File: "empty/empty_card.templ"},
	"radio-fields":                      {Component: lazy(exradiogroup.RadioFields), File: "radiogroup/radio_fields.templ"},
	"input-demo":                        {Component: lazy(exinput.InputDemo), File: "input/input_demo.templ"},
	"input-basic":                       {Component: lazy(exinput.InputBasic), File: "input/input_basic.templ"},
	"input-field":                       {Component: lazy(exinput.InputField), File: "input/input_field.templ"},
	"input-fieldgroup":                  {Component: lazy(exinput.InputFieldgroup), File: "input/input_fieldgroup.templ"},
	"input-disabled":                    {Component: lazy(exinput.InputDisabled), File: "input/input_disabled.templ"},
	"input-invalid":                     {Component: lazy(exinput.InputInvalid), File: "input/input_invalid.templ"},
	"input-file":                        {Component: lazy(exinput.InputFile), File: "input/input_file.templ"},
	"input-inline":                      {Component: lazy(exinput.InputInline), File: "input/input_inline.templ"},
	"input-grid":                        {Component: lazy(exinput.InputGrid), File: "input/input_grid.templ"},
	"input-required":                    {Component: lazy(exinput.InputRequired), File: "input/input_required.templ"},
	"input-badge":                       {Component: lazy(exinput.InputBadge), File: "input/input_badge.templ"},
	"input-input-group":                 {Component: lazy(exinput.InputInputGroup), File: "input/input_input_group.templ"},
	"input-button-group":                {Component: lazy(exinput.InputButtonGroup), File: "input/input_button_group.templ"},
	"input-form":                        {Component: lazy(exinput.InputForm), File: "input/input_form.templ"},
	"icon-demo":                         {Component: lazy(exicon.IconDemo), File: "icon/icon_demo.templ"},
	"icon-colored":                      {Component: lazy(exicon.IconColored), File: "icon/icon_colored.templ"},
	"icon-filled":                       {Component: lazy(exicon.IconFilled), File: "icon/icon_filled.templ"},
	"icon-sizes":                        {Component: lazy(exicon.IconSizes), File: "icon/icon_sizes.templ"},
	"hover-card-demo":                   {Component: lazy(exhovercard.HoverCardDemo), File: "hovercard/hovercard_demo.templ"},
	"hover-card-sides":                  {Component: lazy(exhovercard.HoverCardSides), File: "hovercard/hovercard_sides.templ"},
	"field-demo":                        {Component: lazy(exfield.FieldDemo), File: "field/field_demo.templ"},
	"field-input":                       {Component: lazy(exfield.FieldInput), File: "field/field_input.templ"},
	"field-textarea":                    {Component: lazy(exfield.FieldTextarea), File: "field/field_textarea.templ"},
	"field-select":                      {Component: lazy(exfield.FieldSelect), File: "field/field_select.templ"},
	"switch-demo":                       {Component: lazy(exswitchex.SwitchDemo), File: "switchex/switch_demo.templ"},
	"switch-description":                {Component: lazy(exswitchex.SwitchDescription), File: "switchex/switch_description.templ"},
	"switch-choice-card":                {Component: lazy(exswitchex.SwitchChoiceCard), File: "switchex/switch_choice_card.templ"},
	"switch-disabled":                   {Component: lazy(exswitchex.SwitchDisabled), File: "switchex/switch_disabled.templ"},
	"switch-invalid":                    {Component: lazy(exswitchex.SwitchInvalid), File: "switchex/switch_invalid.templ"},
	"switch-sizes":                      {Component: lazy(exswitchex.SwitchSizes), File: "switchex/switch_sizes.templ"},
	"slider-demo":                       {Component: lazy(exslider.SliderDemo), File: "slider/slider_demo.templ"},
	"slider-range":                      {Component: lazy(exslider.SliderRange), File: "slider/slider_range.templ"},
	"slider-multiple":                   {Component: lazy(exslider.SliderMultiple), File: "slider/slider_multiple.templ"},
	"slider-vertical":                   {Component: lazy(exslider.SliderVertical), File: "slider/slider_vertical.templ"},
	"slider-controlled":                 {Component: lazy(exslider.SliderControlled), File: "slider/slider_controlled.templ"},
	"slider-disabled":                   {Component: lazy(exslider.SliderDisabled), File: "slider/slider_disabled.templ"},
	"field-slider":                      {Component: lazy(exfield.FieldSlider), File: "field/field_slider.templ"},
	"field-fieldset":                    {Component: lazy(exfield.FieldFieldset), File: "field/field_fieldset.templ"},
	"field-checkbox":                    {Component: lazy(exfield.FieldCheckbox), File: "field/field_checkbox.templ"},
	"field-radio":                       {Component: lazy(exfield.FieldRadio), File: "field/field_radio.templ"},
	"field-switch":                      {Component: lazy(exfield.FieldSwitch), File: "field/field_switch.templ"},
	"field-choice-card":                 {Component: lazy(exfield.FieldChoiceCard), File: "field/field_choice_card.templ"},
	"field-group":                       {Component: lazy(exfield.FieldGroupExample), File: "field/field_group.templ"},
	"field-responsive":                  {Component: lazy(exfield.FieldResponsive), File: "field/field_responsive.templ"},
	"empty-demo":                        {Component: lazy(exempty.EmptyDemo), File: "empty/empty_demo.templ"},
	"empty-outline":                     {Component: lazy(exempty.EmptyOutline), File: "empty/empty_outline.templ"},
	"empty-background":                  {Component: lazy(exempty.EmptyBackground), File: "empty/empty_background.templ"},
	"empty-avatar":                      {Component: lazy(exempty.EmptyAvatar), File: "empty/empty_avatar.templ"},
	"empty-avatar-group":                {Component: lazy(exempty.EmptyAvatarGroup), File: "empty/empty_avatar_group.templ"},
	"empty-input-group":                 {Component: lazy(exempty.EmptyInputGroup), File: "empty/empty_input_group.templ"},
	"dropdown-menu-demo":                {Component: lazy(exdropdownmenu.DropdownMenuDemo), File: "dropdownmenu/dropdownmenu_demo.templ"},
	"dropdown-menu-basic":               {Component: lazy(exdropdownmenu.DropdownMenuBasic), File: "dropdownmenu/dropdownmenu_basic.templ"},
	"dropdown-menu-submenu":             {Component: lazy(exdropdownmenu.DropdownMenuSubmenu), File: "dropdownmenu/dropdownmenu_submenu.templ"},
	"dropdown-menu-shortcuts":           {Component: lazy(exdropdownmenu.DropdownMenuShortcuts), File: "dropdownmenu/dropdownmenu_shortcuts.templ"},
	"dropdown-menu-icons":               {Component: lazy(exdropdownmenu.DropdownMenuIcons), File: "dropdownmenu/dropdownmenu_icons.templ"},
	"dropdown-menu-checkboxes":          {Component: lazy(exdropdownmenu.DropdownMenuCheckboxes), File: "dropdownmenu/dropdownmenu_checkboxes.templ"},
	"dropdown-menu-checkboxes-icons":    {Component: lazy(exdropdownmenu.DropdownMenuCheckboxesIcons), File: "dropdownmenu/dropdownmenu_checkboxes_icons.templ"},
	"dropdown-menu-radio-group":         {Component: lazy(exdropdownmenu.DropdownMenuRadioGroupExample), File: "dropdownmenu/dropdownmenu_radio_group.templ"},
	"dropdown-menu-radio-icons":         {Component: lazy(exdropdownmenu.DropdownMenuRadioIcons), File: "dropdownmenu/dropdownmenu_radio_icons.templ"},
	"dropdown-menu-destructive":         {Component: lazy(exdropdownmenu.DropdownMenuDestructive), File: "dropdownmenu/dropdownmenu_destructive.templ"},
	"dropdown-menu-avatar":              {Component: lazy(exdropdownmenu.DropdownMenuAvatar), File: "dropdownmenu/dropdownmenu_avatar.templ"},
	"dropdown-menu-complex":             {Component: lazy(exdropdownmenu.DropdownMenuComplex), File: "dropdownmenu/dropdownmenu_complex.templ"},
	"dialog-demo":                       {Component: lazy(exdialog.DialogDemo), File: "dialog/dialog_demo.templ"},
	"dialog-close-button":               {Component: lazy(exdialog.DialogCloseButton), File: "dialog/dialog_close_button.templ"},
	"dialog-no-close-button":            {Component: lazy(exdialog.DialogNoCloseButton), File: "dialog/dialog_no_close_button.templ"},
	"dialog-sticky-footer":              {Component: lazy(exdialog.DialogStickyFooter), File: "dialog/dialog_sticky_footer.templ"},
	"dialog-scrollable-content":         {Component: lazy(exdialog.DialogScrollableContent), File: "dialog/dialog_scrollable_content.templ"},
	"alert-dialog-demo":                 {Component: lazy(exalertdialog.AlertDialogDemo), File: "alertdialog/alert_dialog_demo.templ"},
	"alert-dialog-basic":                {Component: lazy(exalertdialog.AlertDialogBasic), File: "alertdialog/alert_dialog_basic.templ"},
	"alert-dialog-small":                {Component: lazy(exalertdialog.AlertDialogSmall), File: "alertdialog/alert_dialog_small.templ"},
	"alert-dialog-media":                {Component: lazy(exalertdialog.AlertDialogWithMedia), File: "alertdialog/alert_dialog_media.templ"},
	"alert-dialog-small-media":          {Component: lazy(exalertdialog.AlertDialogSmallWithMedia), File: "alertdialog/alert_dialog_small_media.templ"},
	"alert-dialog-destructive":          {Component: lazy(exalertdialog.AlertDialogDestructive), File: "alertdialog/alert_dialog_destructive.templ"},
	"drawer-demo":                       {Component: lazy(exdrawer.DrawerDemo), File: "drawer/drawer_demo.templ", Style: "base-rhea"},
	"drawer-sides":                      {Component: lazy(exdrawer.DrawerSides), File: "drawer/drawer_sides.templ", Style: "base-rhea"},
	"drawer-swipe-handle":               {Component: lazy(exdrawer.DrawerSwipeHandle), File: "drawer/drawer_swipe_handle.templ", Style: "base-rhea"},
	"drawer-nested":                     {Component: lazy(exdrawer.DrawerNested), File: "drawer/drawer_nested.templ", Style: "base-rhea"},
	"drawer-non-modal":                  {Component: lazy(exdrawer.DrawerNonModal), File: "drawer/drawer_non_modal.templ", Style: "base-rhea"},
	"drawer-snap-points":                {Component: lazy(exdrawer.DrawerSnapPoints), File: "drawer/drawer_snap_points.templ", Style: "base-rhea"},
	"drawer-dialog":                     {Component: lazy(exdrawer.DrawerDialog), File: "drawer/drawer_dialog.templ", Style: "base-rhea"},
	"command-demo":                      {Component: lazy(excommand.CommandDemo), File: "command/command_demo.templ"},
	"command-basic":                     {Component: lazy(excommand.CommandBasic), File: "command/command_basic.templ"},
	"command-shortcuts":                 {Component: lazy(excommand.CommandShortcuts), File: "command/command_shortcuts.templ"},
	"command-groups":                    {Component: lazy(excommand.CommandGroups), File: "command/command_groups.templ"},
	"command-scrollable":                {Component: lazy(excommand.CommandScrollable), File: "command/command_scrollable.templ"},
	"accordion-example":                 {Component: lazy(exaccordion.AccordionExample), File: "accordion/accordion_example.templ"},
	"alert-dialog-example":              {Component: lazy(exalertdialog.AlertDialogExample), File: "alertdialog/alert_dialog_example.templ"},
	"alert-example":                     {Component: lazy(exalert.AlertExample), File: "alert/alert_example.templ"},
	"aspect-ratio-example":              {Component: lazy(exaspectratio.AspectRatioExample), File: "aspectratio/aspect_ratio_example.templ"},
	"avatar-example":                    {Component: lazy(exavatar.AvatarExample), File: "avatar/avatar_example.templ"},
	"badge-example":                     {Component: lazy(exbadge.BadgeExample), File: "badge/badge_example.templ"},
	"breadcrumb-example":                {Component: lazy(exbreadcrumb.BreadcrumbExample), File: "breadcrumb/breadcrumb_example.templ"},
	"button-example":                    {Component: lazy(exbutton.ButtonExample), File: "button/button_example.templ"},
	"button-group-example":              {Component: lazy(exbuttongroup.ButtonGroupExample), File: "buttongroup/button_group_example.templ"},
	"calendar-example":                  {Component: lazy(excalendar.CalendarExample), File: "calendar/calendar_example.templ"},
	"accordion-rtl":                     {Component: lazy(exaccordion.AccordionRtl), File: "accordion/accordion_rtl.templ", RTL: true},
	"alert-dialog-rtl":                  {Component: lazy(exalertdialog.AlertDialogRtl), File: "alertdialog/alert_dialog_rtl.templ", RTL: true},
	"alert-rtl":                         {Component: lazy(exalert.AlertRtl), File: "alert/alert_rtl.templ", RTL: true},
	"aspect-ratio-rtl":                  {Component: lazy(exaspectratio.AspectRatioRtl), File: "aspectratio/aspect_ratio_rtl.templ", RTL: true},
	"avatar-rtl":                        {Component: lazy(exavatar.AvatarRtl), File: "avatar/avatar_rtl.templ", RTL: true},
	"badge-rtl":                         {Component: lazy(exbadge.BadgeRtl), File: "badge/badge_rtl.templ", RTL: true},
	"breadcrumb-rtl":                    {Component: lazy(exbreadcrumb.BreadcrumbRtl), File: "breadcrumb/breadcrumb_rtl.templ", RTL: true},
	"button-group-rtl":                  {Component: lazy(exbuttongroup.ButtonGroupRtl), File: "buttongroup/button_group_rtl.templ", RTL: true},
	"button-rtl":                        {Component: lazy(exbutton.ButtonRtl), File: "button/button_rtl.templ", RTL: true},
	"calendar-rtl":                      {Component: lazy(excalendar.CalendarRtl), File: "calendar/calendar_rtl.templ", RTL: true},
	"card-rtl":                          {Component: lazy(excard.CardRtl), File: "card/card_rtl.templ", RTL: true},
	"carousel-rtl":                      {Component: lazy(excarousel.CarouselRtl), File: "carousel/carousel_rtl.templ", RTL: true},
	"chart-rtl":                         {Component: lazy(exchart.ChartRtl), File: "chart/chart_rtl.templ", RTL: true},
	"sidebar-rtl":                       {Component: lazy(exsidebar.SidebarRtl), File: "sidebar/sidebar_rtl.templ", RTL: true},
	"navigation-menu-rtl":               {Component: lazy(exnavigationmenu.NavigationMenuRtl), File: "navigationmenu/navigation_menu_rtl.templ", RTL: true},
	"menubar-rtl":                       {Component: lazy(exmenubar.MenubarRtl), File: "menubar/menubar_rtl.templ", RTL: true},
	"typography-rtl":                    {Component: lazy(extypography.TypographyRtl), File: "typography/typography_rtl.templ"},
	"table-rtl":                         {Component: lazy(extable.TableRtl), File: "table/table_rtl.templ", RTL: true},
	"checkbox-rtl":                      {Component: lazy(excheckbox.CheckboxRtl), File: "checkbox/checkbox_rtl.templ", RTL: true},
	"collapsible-rtl":                   {Component: lazy(excollapsible.CollapsibleRtl), File: "collapsible/collapsible_rtl.templ", RTL: true},
	"combobox-rtl":                      {Component: lazy(excombobox.ComboboxRtl), File: "combobox/combobox_rtl.templ", RTL: true},
	"command-rtl":                       {Component: lazy(excommand.CommandRtl), File: "command/command_rtl.templ", RTL: true},
	"context-menu-rtl":                  {Component: lazy(excontextmenu.ContextMenuRtl), File: "contextmenu/context_menu_rtl.templ", RTL: true},
	"data-table-rtl":                    {Component: lazy(exdatatable.DataTableRtl), File: "datatable/data_table_rtl.templ", RTL: true},
	"date-picker-rtl":                   {Component: lazy(exdatepicker.DatePickerRtl), File: "datepicker/date_picker_rtl.templ", RTL: true},
	"select-rtl":                        {Component: lazy(exselectex.SelectRtl), File: "selectex/select_rtl.templ", RTL: true},
	"tabs-rtl":                          {Component: lazy(extabs.TabsRtl), File: "tabs/tabs_rtl.templ", RTL: true},
	"popover-rtl":                       {Component: lazy(expopover.PopoverRtl), File: "popover/popover_rtl.templ", RTL: true},
	"tooltip-rtl":                       {Component: lazy(extooltip.TooltipRtl), File: "tooltip/tooltip_rtl.templ", RTL: true},
	"radio-group-rtl":                   {Component: lazy(exradiogroup.RadioGroupRtl), File: "radiogroup/radio_group_rtl.templ", RTL: true},
	"sheet-rtl":                         {Component: lazy(exsheet.SheetRtl), File: "sheet/sheet_rtl.templ", RTL: true},
	"dialog-rtl":                        {Component: lazy(exdialog.DialogRtl), File: "dialog/dialog_rtl.templ", RTL: true},
	"drawer-rtl":                        {Component: lazy(exdrawer.DrawerRtl), File: "drawer/drawer_rtl.templ", RTL: true},
	"dropdown-menu-rtl":                 {Component: lazy(exdropdownmenu.DropdownMenuRtl), File: "dropdownmenu/dropdown_menu_rtl.templ", RTL: true},
	"empty-rtl":                         {Component: lazy(exempty.EmptyRtl), File: "empty/empty_rtl.templ", RTL: true},
	"field-rtl":                         {Component: lazy(exfield.FieldRtl), File: "field/field_rtl.templ", RTL: true},
	"hover-card-rtl":                    {Component: lazy(exhovercard.HoverCardRtl), File: "hovercard/hover_card_rtl.templ", RTL: true},
	"input-group-rtl":                   {Component: lazy(exinputgroup.InputGroupRtl), File: "inputgroup/input_group_rtl.templ", RTL: true},
	"input-otp-rtl":                     {Component: lazy(exinputotp.InputOTPRtl), File: "inputotp/input_otp_rtl.templ", RTL: true},
	"input-rtl":                         {Component: lazy(exinput.InputRtl), File: "input/input_rtl.templ", RTL: true},
	"item-rtl":                          {Component: lazy(exitem.ItemRtl), File: "item/item_rtl.templ", RTL: true},
	"kbd-rtl":                           {Component: lazy(exkbd.KbdRtl), File: "kbd/kbd_rtl.templ", RTL: true},
	"label-rtl":                         {Component: lazy(exlabel.LabelRtl), File: "label/label_rtl.templ", RTL: true},
	"native-select-rtl":                 {Component: lazy(exnativeselect.NativeSelectRtl), File: "nativeselect/native_select_rtl.templ", RTL: true},
	"separator-rtl":                     {Component: lazy(exseparator.SeparatorRtl), File: "separator/separator_rtl.templ", RTL: true},
	"skeleton-rtl":                      {Component: lazy(exskeleton.SkeletonRtl), File: "skeleton/skeleton_rtl.templ", RTL: true},
	"slider-rtl":                        {Component: lazy(exslider.SliderRtl), File: "slider/slider_rtl.templ", RTL: true},
	"spinner-rtl":                       {Component: lazy(exspinner.SpinnerRtl), File: "spinner/spinner_rtl.templ", RTL: true},
	"switch-rtl":                        {Component: lazy(exswitchex.SwitchRtl), File: "switchex/switch_rtl.templ", RTL: true},
	"textarea-rtl":                      {Component: lazy(extextarea.TextareaRtl), File: "textarea/textarea_rtl.templ", RTL: true},
	"toggle-rtl":                        {Component: lazy(extoggle.ToggleRtl), File: "toggle/toggle_rtl.templ", RTL: true},
	"shimmer-rtl":                       {Component: lazy(exshimmer.ShimmerRtl), File: "shimmer/shimmer_rtl.templ"},
	"scroll-fade-rtl":                   {Component: lazy(exscrollfade.ScrollFadeRtl), File: "scrollfade/scroll_fade_rtl.templ"},
	"scroll-area-rtl":                   {Component: lazy(exscrollarea.ScrollAreaRtl), File: "scrollarea/scroll_area_rtl.templ", RTL: true},
	"toggle-group-rtl":                  {Component: lazy(extogglegroup.ToggleGroupRtl), File: "togglegroup/toggle_group_rtl.templ", RTL: true},
	"pagination-rtl":                    {Component: lazy(expagination.PaginationRtl), File: "pagination/pagination_rtl.templ", RTL: true},
	"card-example":                      {Component: lazy(excard.CardExample), File: "card/card_example.templ"},
	"carousel-example":                  {Component: lazy(excarousel.CarouselExample), File: "carousel/carousel_example.templ"},
	"chart-example-page":                {Component: lazy(exchart.ChartExamplePage), File: "chart/chart_example_page.templ"},
	"checkbox-example":                  {Component: lazy(excheckbox.CheckboxExample), File: "checkbox/checkbox_example.templ"},
	"collapsible-example":               {Component: lazy(excollapsible.CollapsibleExample), File: "collapsible/collapsible_example.templ"},
	"combobox-example":                  {Component: lazy(excombobox.ComboboxExample), File: "combobox/combobox_example.templ"},
	"command-example":                   {Component: lazy(excommand.CommandExample), File: "command/command_example.templ"},
	"context-menu-example":              {Component: lazy(excontextmenu.ContextMenuExample), File: "contextmenu/contextmenu_example.templ"},
	"dialog-example":                    {Component: lazy(exdialog.DialogExample), File: "dialog/dialog_example.templ"},
	"drawer-example":                    {Component: lazy(exdrawer.DrawerExample), File: "drawer/drawer_example.templ"},
	"dropdown-menu-example":             {Component: lazy(exdropdownmenu.DropdownMenuExample), File: "dropdownmenu/dropdownmenu_example.templ"},
	"empty-example":                     {Component: lazy(exempty.EmptyExample), File: "empty/empty_example.templ"},
	"field-example":                     {Component: lazy(exfield.FieldExample), File: "field/field_example.templ"},
	"hover-card-example":                {Component: lazy(exhovercard.HoverCardExample), File: "hovercard/hovercard_example.templ"},
	"input-example":                     {Component: lazy(exinput.InputExample), File: "input/input_example.templ"},
	"input-group-example":               {Component: lazy(exinputgroup.InputGroupExample), File: "inputgroup/inputgroup_example.templ"},
	"input-otp-example":                 {Component: lazy(exinputotp.InputOTPExample), File: "inputotp/input_otp_example.templ"},
	"item-example":                      {Component: lazy(exitem.ItemExample), File: "item/item_example.templ"},
	"kbd-example":                       {Component: lazy(exkbd.KbdExample), File: "kbd/kbd_example.templ"},
	"label-example":                     {Component: lazy(exlabel.LabelExample), File: "label/label_example.templ"},
	"pagination-example":                {Component: lazy(expagination.PaginationExample), File: "pagination/pagination_example.templ"},
	"popover-example":                   {Component: lazy(expopover.PopoverExample), File: "popover/popover_example.templ"},
	"progress-example":                  {Component: lazy(exprogress.ProgressExample), File: "progress/progress_example.templ"},
	"radio-group-example":               {Component: lazy(exradiogroup.RadioGroupExample), File: "radiogroup/radio_group_example.templ"},
	"select-example":                    {Component: lazy(exselectex.SelectExample), File: "selectex/select_example.templ"},
	"separator-example":                 {Component: lazy(exseparator.SeparatorExample), File: "separator/separator_example.templ"},
	"sheet-example":                     {Component: lazy(exsheet.SheetExample), File: "sheet/sheet_example.templ"},
	"sidebar-example":                   {Component: lazy(exsidebar.SidebarExample), File: "sidebar/sidebar_example.templ"},
	"sidebar-floating-example":          {Component: lazy(exsidebar.SidebarFloatingExample), File: "sidebar/sidebar_floating_example.templ"},
	"sidebar-icon-example":              {Component: lazy(exsidebar.SidebarIconExample), File: "sidebar/sidebar_icon_example.templ"},
	"sidebar-inset-example":             {Component: lazy(exsidebar.SidebarInsetExample), File: "sidebar/sidebar_inset_example.templ"},
	"skeleton-example":                  {Component: lazy(exskeleton.SkeletonExample), File: "skeleton/skeleton_example.templ"},
	"slider-example":                    {Component: lazy(exslider.SliderExample), File: "slider/slider_example.templ"},
	"spinner-example":                   {Component: lazy(exspinner.SpinnerExample), File: "spinner/spinner_example.templ"},
	"switch-example":                    {Component: lazy(exswitchex.SwitchExample), File: "switchex/switch_example.templ"},
	"table-example":                     {Component: lazy(extable.TableExample), File: "table/table_example.templ"},
	"tabs-example":                      {Component: lazy(extabs.TabsExample), File: "tabs/tabs_example.templ"},
	"textarea-example":                  {Component: lazy(extextarea.TextareaExample), File: "textarea/textarea_example.templ"},
	"toast-example":                     {Component: lazy(extoast.ToastExample), File: "toast/toast_example.templ"},
	"toggle-example":                    {Component: lazy(extoggle.ToggleExample), File: "toggle/toggle_example.templ"},
	"toggle-group-example":              {Component: lazy(extogglegroup.ToggleGroupExample), File: "togglegroup/togglegroup_example.templ"},
	"tooltip-example":                   {Component: lazy(extooltip.TooltipExample), File: "tooltip/tooltip_example.templ"},
	"date-picker-demo":                  {Component: lazy(exdatepicker.DatePickerDemo), File: "datepicker/date_picker_demo.templ"},
	"date-picker-basic":                 {Component: lazy(exdatepicker.DatePickerBasic), File: "datepicker/date_picker_basic.templ"},
	"date-picker-range":                 {Component: lazy(exdatepicker.DatePickerRange), File: "datepicker/date_picker_range.templ"},
	"date-picker-dob":                   {Component: lazy(exdatepicker.DatePickerDob), File: "datepicker/date_picker_dob.templ"},
	"date-picker-input":                 {Component: lazy(exdatepicker.DatePickerInput), File: "datepicker/date_picker_input.templ"},
	"date-picker-time":                  {Component: lazy(exdatepicker.DatePickerTime), File: "datepicker/date_picker_time.templ"},
	"context-menu-demo":                 {Component: lazy(excontextmenu.ContextMenuDemo), File: "contextmenu/contextmenu_demo.templ"},
	"context-menu-basic":                {Component: lazy(excontextmenu.ContextMenuBasic), File: "contextmenu/contextmenu_basic.templ"},
	"context-menu-submenu":              {Component: lazy(excontextmenu.ContextMenuSubmenu), File: "contextmenu/contextmenu_submenu.templ"},
	"context-menu-shortcuts":            {Component: lazy(excontextmenu.ContextMenuShortcuts), File: "contextmenu/contextmenu_shortcuts.templ"},
	"context-menu-groups":               {Component: lazy(excontextmenu.ContextMenuGroups), File: "contextmenu/contextmenu_groups.templ"},
	"context-menu-icons":                {Component: lazy(excontextmenu.ContextMenuIcons), File: "contextmenu/contextmenu_icons.templ"},
	"context-menu-checkboxes":           {Component: lazy(excontextmenu.ContextMenuCheckboxes), File: "contextmenu/contextmenu_checkboxes.templ"},
	"context-menu-radio":                {Component: lazy(excontextmenu.ContextMenuRadio), File: "contextmenu/contextmenu_radio.templ"},
	"context-menu-destructive":          {Component: lazy(excontextmenu.ContextMenuDestructive), File: "contextmenu/contextmenu_destructive.templ"},
	"context-menu-sides":                {Component: lazy(excontextmenu.ContextMenuSides), File: "contextmenu/contextmenu_sides.templ"},
	"combobox-demo":                     {Component: lazy(excombobox.ComboboxDemo), File: "combobox/combobox_demo.templ"},
	"combobox-basic":                    {Component: lazy(excombobox.ComboboxBasic), File: "combobox/combobox_basic.templ"},
	"combobox-multiple":                 {Component: lazy(excombobox.ComboboxMultiple), File: "combobox/combobox_multiple.templ"},
	"combobox-clear":                    {Component: lazy(excombobox.ComboboxClear), File: "combobox/combobox_clear.templ"},
	"combobox-groups":                   {Component: lazy(excombobox.ComboboxGroups), File: "combobox/combobox_groups.templ"},
	"combobox-custom":                   {Component: lazy(excombobox.ComboboxCustom), File: "combobox/combobox_custom.templ"},
	"combobox-invalid":                  {Component: lazy(excombobox.ComboboxInvalid), File: "combobox/combobox_invalid.templ"},
	"combobox-disabled":                 {Component: lazy(excombobox.ComboboxDisabled), File: "combobox/combobox_disabled.templ"},
	"combobox-auto-highlight":           {Component: lazy(excombobox.ComboboxAutoHighlight), File: "combobox/combobox_auto_highlight.templ"},
	"combobox-popup":                    {Component: lazy(excombobox.ComboboxPopup), File: "combobox/combobox_popup.templ"},
	"combobox-input-group":              {Component: lazy(excombobox.ComboboxInputGroup), File: "combobox/combobox_input_group.templ"},
	"carousel-demo":                     {Component: lazy(excarousel.CarouselDemo), File: "carousel/carousel_demo.templ"},
	"carousel-size":                     {Component: lazy(excarousel.CarouselSize), File: "carousel/carousel_size.templ"},
	"carousel-spacing":                  {Component: lazy(excarousel.CarouselSpacing), File: "carousel/carousel_spacing.templ"},
	"carousel-orientation":              {Component: lazy(excarousel.CarouselOrientation), File: "carousel/carousel_orientation.templ"},
	"carousel-api":                      {Component: lazy(excarousel.CarouselApi), File: "carousel/carousel_api.templ"},
	"carousel-plugin":                   {Component: lazy(excarousel.CarouselPlugin), File: "carousel/carousel_plugin.templ"},
	"calendar-demo":                     {Component: lazy(excalendar.CalendarDemo), File: "calendar/calendar_demo.templ"},
	"calendar-basic":                    {Component: lazy(excalendar.CalendarBasic), File: "calendar/calendar_basic.templ"},
	"calendar-range":                    {Component: lazy(excalendar.CalendarRange), File: "calendar/calendar_range.templ"},
	"calendar-caption":                  {Component: lazy(excalendar.CalendarCaption), File: "calendar/calendar_caption.templ"},
	"calendar-presets":                  {Component: lazy(excalendar.CalendarPresets), File: "calendar/calendar_presets.templ"},
	"calendar-time":                     {Component: lazy(excalendar.CalendarTime), File: "calendar/calendar_time.templ"},
	"calendar-booked-dates":             {Component: lazy(excalendar.CalendarBookedDates), File: "calendar/calendar_booked_dates.templ"},
	"calendar-custom-days":              {Component: lazy(excalendar.CalendarCustomCellSize), File: "calendar/calendar_custom_days.templ"},
	"calendar-week-numbers":             {Component: lazy(excalendar.CalendarWeekNumbers), File: "calendar/calendar_week_numbers.templ"},
	"button-group-orientation":          {Component: lazy(exbuttongroup.ButtonGroupOrientation), File: "buttongroup/buttongroup_orientation.templ"},
	"button-group-size":                 {Component: lazy(exbuttongroup.ButtonGroupSize), File: "buttongroup/buttongroup_size.templ"},
	"button-group-nested":               {Component: lazy(exbuttongroup.ButtonGroupNested), File: "buttongroup/buttongroup_nested.templ"},
	"button-group-separator":            {Component: lazy(exbuttongroup.ButtonGroupSeparatorExample), File: "buttongroup/buttongroup_separator.templ"},
	"button-group-split":                {Component: lazy(exbuttongroup.ButtonGroupSplit), File: "buttongroup/buttongroup_split.templ"},
	"button-group-input":                {Component: lazy(exbuttongroup.ButtonGroupInput), File: "buttongroup/buttongroup_input.templ"},
	"button-group-input-group":          {Component: lazy(exbuttongroup.ButtonGroupInputGroup), File: "buttongroup/buttongroup_input_group.templ"},
	"button-group-dropdown":             {Component: lazy(exbuttongroup.ButtonGroupDropdown), File: "buttongroup/buttongroup_dropdown.templ"},
	"button-group-select":               {Component: lazy(exbuttongroup.ButtonGroupSelect), File: "buttongroup/buttongroup_select.templ"},
	"button-group-popover":              {Component: lazy(exbuttongroup.ButtonGroupPopover), File: "buttongroup/buttongroup_popover.templ"},
	"card-demo":                         {Component: lazy(excard.CardDemo), File: "card/card_demo.templ"},
	"card-small":                        {Component: lazy(excard.CardSmall), File: "card/card_small.templ"},
	"card-spacing":                      {Component: lazy(excard.CardSpacing), File: "card/card_spacing.templ"},
	"card-edge-to-edge":                 {Component: lazy(excard.CardEdgeToEdge), File: "card/card_edge_to_edge.templ"},
	"card-image":                        {Component: lazy(excard.CardImage), File: "card/card_image.templ"},
	"checkbox-demo":                     {Component: lazy(excheckbox.CheckboxDemo), File: "checkbox/checkbox_demo.templ"},
	"checkbox-basic":                    {Component: lazy(excheckbox.CheckboxBasic), File: "checkbox/checkbox_basic.templ"},
	"checkbox-invalid":                  {Component: lazy(excheckbox.CheckboxInvalid), File: "checkbox/checkbox_invalid.templ"},
	"checkbox-description":              {Component: lazy(excheckbox.CheckboxDescription), File: "checkbox/checkbox_description.templ"},
	"checkbox-disabled":                 {Component: lazy(excheckbox.CheckboxDisabled), File: "checkbox/checkbox_disabled.templ"},
	"checkbox-group":                    {Component: lazy(excheckbox.CheckboxGroup), File: "checkbox/checkbox_group.templ"},
	"checkbox-table":                    {Component: lazy(excheckbox.CheckboxTable), File: "checkbox/checkbox_table.templ"},
	"collapsible-demo":                  {Component: lazy(excollapsible.CollapsibleDemo), File: "collapsible/collapsible_demo.templ"},
	"collapsible-basic":                 {Component: lazy(excollapsible.CollapsibleBasic), File: "collapsible/collapsible_basic.templ"},
	"collapsible-settings":              {Component: lazy(excollapsible.CollapsibleSettings), File: "collapsible/collapsible_settings.templ"},
	"collapsible-file-tree":             {Component: lazy(excollapsible.CollapsibleFileTree), File: "collapsible/collapsible_file_tree.templ"},
	"accordion-demo":                    {Component: lazy(exaccordion.AccordionDemo), File: "accordion/accordion_demo.templ"},
	"accordion-basic":                   {Component: lazy(exaccordion.AccordionBasic), File: "accordion/accordion_basic.templ"},
	"accordion-multiple":                {Component: lazy(exaccordion.AccordionMultiple), File: "accordion/accordion_multiple.templ"},
	"accordion-disabled":                {Component: lazy(exaccordion.AccordionDisabled), File: "accordion/accordion_disabled.templ"},
	"accordion-borders":                 {Component: lazy(exaccordion.AccordionBorders), File: "accordion/accordion_borders.templ"},
	"accordion-card":                    {Component: lazy(exaccordion.AccordionCard), File: "accordion/accordion_card.templ"},
	"alert-demo":                        {Component: lazy(exalert.AlertDemo), File: "alert/alert_demo.templ"},
	"alert-basic":                       {Component: lazy(exalert.AlertBasic), File: "alert/alert_basic.templ"},
	"alert-destructive":                 {Component: lazy(exalert.AlertDestructive), File: "alert/alert_destructive.templ"},
	"alert-action":                      {Component: lazy(exalert.AlertAction), File: "alert/alert_action.templ"},
	"alert-colors":                      {Component: lazy(exalert.AlertColors), File: "alert/alert_colors.templ"},
	"aspect-ratio-demo":                 {Component: lazy(exaspectratio.AspectRatioDemo), File: "aspectratio/aspect_ratio_demo.templ"},
	"aspect-ratio-square":               {Component: lazy(exaspectratio.AspectRatioSquare), File: "aspectratio/aspect_ratio_square.templ"},
	"aspect-ratio-portrait":             {Component: lazy(exaspectratio.AspectRatioPortrait), File: "aspectratio/aspect_ratio_portrait.templ"},
	"avatar-demo":                       {Component: lazy(exavatar.AvatarDemo), File: "avatar/avatar_demo.templ"},
	"avatar-basic":                      {Component: lazy(exavatar.AvatarBasic), File: "avatar/avatar_basic.templ"},
	"avatar-badge":                      {Component: lazy(exavatar.AvatarBadgeExample), File: "avatar/avatar_badge.templ"},
	"avatar-badge-icon":                 {Component: lazy(exavatar.AvatarBadgeIcon), File: "avatar/avatar_badge_icon.templ"},
	"avatar-group":                      {Component: lazy(exavatar.AvatarGroup), File: "avatar/avatar_group.templ"},
	"avatar-group-count":                {Component: lazy(exavatar.AvatarGroupCount), File: "avatar/avatar_group_count.templ"},
	"avatar-group-count-icon":           {Component: lazy(exavatar.AvatarGroupCountIcon), File: "avatar/avatar_group_count_icon.templ"},
	"avatar-size":                       {Component: lazy(exavatar.AvatarSize), File: "avatar/avatar_size.templ"},
	"avatar-dropdown":                   {Component: lazy(exavatar.AvatarDropdown), File: "avatar/avatar_dropdown.templ"},
	"badge-demo":                        {Component: lazy(exbadge.BadgeDemo), File: "badge/badge_demo.templ"},
	"badge-variants":                    {Component: lazy(exbadge.BadgeVariants), File: "badge/badge_variants.templ"},
	"badge-icon":                        {Component: lazy(exbadge.BadgeIcon), File: "badge/badge_icon.templ"},
	"badge-spinner":                     {Component: lazy(exbadge.BadgeSpinner), File: "badge/badge_spinner.templ"},
	"badge-link":                        {Component: lazy(exbadge.BadgeLink), File: "badge/badge_link.templ"},
	"badge-colors":                      {Component: lazy(exbadge.BadgeColors), File: "badge/badge_colors.templ"},
	"breadcrumb-demo":                   {Component: lazy(exbreadcrumb.BreadcrumbDemo), File: "breadcrumb/breadcrumb_demo.templ"},
	"breadcrumb-basic":                  {Component: lazy(exbreadcrumb.BreadcrumbBasic), File: "breadcrumb/breadcrumb_basic.templ"},
	"breadcrumb-separator":              {Component: lazy(exbreadcrumb.BreadcrumbSeparator), File: "breadcrumb/breadcrumb_separator.templ"},
	"breadcrumb-dropdown":               {Component: lazy(exbreadcrumb.BreadcrumbDropdown), File: "breadcrumb/breadcrumb_dropdown.templ"},
	"breadcrumb-ellipsis":               {Component: lazy(exbreadcrumb.BreadcrumbEllipsisDemo), File: "breadcrumb/breadcrumb_ellipsis.templ"},
	"breadcrumb-link":                   {Component: lazy(exbreadcrumb.BreadcrumbLink), File: "breadcrumb/breadcrumb_link.templ"},
	"button-demo":                       {Component: lazy(exbutton.ButtonDemo), File: "button/button_demo.templ"},
	"button-size":                       {Component: lazy(exbutton.ButtonSize), File: "button/button_size.templ"},
	"button-default":                    {Component: lazy(exbutton.ButtonDefault), File: "button/button_default.templ"},
	"button-outline":                    {Component: lazy(exbutton.ButtonOutline), File: "button/button_outline.templ"},
	"button-secondary":                  {Component: lazy(exbutton.ButtonSecondary), File: "button/button_secondary.templ"},
	"button-ghost":                      {Component: lazy(exbutton.ButtonGhost), File: "button/button_ghost.templ"},
	"button-destructive":                {Component: lazy(exbutton.ButtonDestructive), File: "button/button_destructive.templ"},
	"button-link":                       {Component: lazy(exbutton.ButtonLink), File: "button/button_link.templ"},
	"button-icon":                       {Component: lazy(exbutton.ButtonIcon), File: "button/button_icon.templ"},
	"button-with-icon":                  {Component: lazy(exbutton.ButtonWithIcon), File: "button/button_with_icon.templ"},
	"button-rounded":                    {Component: lazy(exbutton.ButtonRounded), File: "button/button_rounded.templ"},
	"button-spinner":                    {Component: lazy(exbutton.ButtonSpinner), File: "button/button_spinner.templ"},
	"button-group-demo":                 {Component: lazy(exbuttongroup.ButtonGroupDemo), File: "buttongroup/buttongroup_demo.templ"},
	"button-render":                     {Component: lazy(exbutton.ButtonRender), File: "button/button_render.templ"},
	"navigation-menu-demo":              {Component: lazy(exnavigationmenu.NavigationMenuDemo), File: "navigationmenu/navigationmenu_demo.templ"},
	"navigation-menu-example":           {Component: lazy(exnavigationmenu.NavigationMenuExample), File: "navigationmenu/navigationmenu_example.templ"},
	"questionnaire-animated":            {Component: lazy(exquestionnaire.QuestionnaireAnimated), File: "questionnaire/questionnaire_animated.templ"},
	"questionnaire-card":                {Component: lazy(exquestionnaire.QuestionnaireCard), File: "questionnaire/questionnaire_card.templ"},
	"questionnaire-conditional":         {Component: lazy(exquestionnaire.QuestionnaireConditional), File: "questionnaire/questionnaire_conditional.templ"},
	"questionnaire-controlled":          {Component: lazy(exquestionnaire.QuestionnaireControlled), File: "questionnaire/questionnaire_controlled.templ"},
	"questionnaire-demo":                {Component: lazy(exquestionnaire.QuestionnaireDemo), File: "questionnaire/questionnaire_demo.templ"},
	"questionnaire-dialog":              {Component: lazy(exquestionnaire.QuestionnaireDialog), File: "questionnaire/questionnaire_dialog.templ"},
	"questionnaire-example":             {Component: lazy(exquestionnaire.QuestionnaireExample), File: "questionnaire/questionnaire_example.templ"},
	"questionnaire-freeform":            {Component: lazy(exquestionnaire.QuestionnaireFreeform), File: "questionnaire/questionnaire_freeform.templ"},
	"questionnaire-multiple":            {Component: lazy(exquestionnaire.QuestionnaireMultiple), File: "questionnaire/questionnaire_multiple.templ"},
	"questionnaire-navigation-state":    {Component: lazy(exquestionnaire.QuestionnaireNavigationState), File: "questionnaire/questionnaire_navigation_state.templ"},
	"questionnaire-progress":            {Component: lazy(exquestionnaire.QuestionnaireProgressExample), File: "questionnaire/questionnaire_progress.templ"},
	"questionnaire-resume":              {Component: lazy(exquestionnaire.QuestionnaireResume), File: "questionnaire/questionnaire_resume.templ"},
	"questionnaire-shortcuts":           {Component: lazy(exquestionnaire.QuestionnaireShortcuts), File: "questionnaire/questionnaire_shortcuts.templ"},
	"questionnaire-skip":                {Component: lazy(exquestionnaire.QuestionnaireSkipExample), File: "questionnaire/questionnaire_skip.templ"},
	"questionnaire-validation":          {Component: lazy(exquestionnaire.QuestionnaireValidation), File: "questionnaire/questionnaire_validation.templ"},
	"typography-demo":                   {Component: lazy(extypography.TypographyDemo), File: "typography/typography_demo.templ"},
	"typography-h1":                     {Component: lazy(extypography.TypographyH1), File: "typography/typography_h1.templ"},
	"typography-h2":                     {Component: lazy(extypography.TypographyH2), File: "typography/typography_h2.templ"},
	"typography-h3":                     {Component: lazy(extypography.TypographyH3), File: "typography/typography_h3.templ"},
	"typography-h4":                     {Component: lazy(extypography.TypographyH4), File: "typography/typography_h4.templ"},
	"typography-p":                      {Component: lazy(extypography.TypographyP), File: "typography/typography_p.templ"},
	"typography-blockquote":             {Component: lazy(extypography.TypographyBlockquote), File: "typography/typography_blockquote.templ"},
	"typography-table":                  {Component: lazy(extypography.TypographyTable), File: "typography/typography_table.templ"},
	"typography-list":                   {Component: lazy(extypography.TypographyList), File: "typography/typography_list.templ"},
	"typography-inline-code":            {Component: lazy(extypography.TypographyInlineCode), File: "typography/typography_inline_code.templ"},
	"typography-lead":                   {Component: lazy(extypography.TypographyLead), File: "typography/typography_lead.templ"},
	"typography-large":                  {Component: lazy(extypography.TypographyLarge), File: "typography/typography_large.templ"},
	"typography-small":                  {Component: lazy(extypography.TypographySmall), File: "typography/typography_small.templ"},
	"typography-muted":                  {Component: lazy(extypography.TypographyMuted), File: "typography/typography_muted.templ"},
}
