package updaters

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/axadrn/shadcn-templ/v2/cmd/shadcn-templ/utils"
)

func TestUpdateScripts(t *testing.T) {
	cwd := t.TempDir()
	write := func(name, content string) {
		t.Helper()
		name = filepath.Join(cwd, name)
		if err := os.MkdirAll(filepath.Dir(name), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(name, []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module example.com/app\n")
	raw := &utils.RawConfig{
		Tailwind: utils.Tailwind{CSS: "assets/css/globals.css"},
		Aliases:  utils.Aliases{Components: "example.com/app/internal/design", Utils: "example.com/app/utils"},
	}
	config, err := utils.ResolveConfigPaths(cwd, raw)
	if err != nil {
		t.Fatal(err)
	}
	write("internal/design/z/z.js", "last")
	write("internal/design/a/a.js", "first")
	write("internal/design/baseui/block.js", "block")
	write("internal/design/a/a.min.js", "ignored")
	write("internal/design/own.js", "ignored")
	write("internal/design/a/nested/x.js", "ignored")
	write("assets/js/custom.js", "keep")
	path, written, err := UpdateScripts(config)
	if err != nil || !written {
		t.Fatalf("first build: written=%v err=%v", written, err)
	}
	want := []byte("// components/baseui/block.js\nblock\n// components/a/a.js\nfirst\n// components/z/z.js\nlast\n")
	got, err := os.ReadFile(path)
	if err != nil || !bytes.Equal(got, want) {
		t.Fatalf("bundle=%q err=%v", got, err)
	}
	sum := sha256.Sum256(want)
	if filepath.Base(path) != fmt.Sprintf("shadcn-templ-%x.js", sum[:8]) {
		t.Fatalf("hash path=%s", path)
	}
	manifestPath := filepath.Join(config.ResolvedPaths.Components, "scripts_bundle.go")
	manifest, _ := os.ReadFile(manifestPath)
	for _, want := range []string{"// Code generated by shadcn-templ bundle. DO NOT EDIT.", "package design", `const bundleSrc = "/assets/js/` + filepath.Base(path) + `"`} {
		if !strings.Contains(string(manifest), want) {
			t.Errorf("manifest missing %q", want)
		}
	}
	persisted, err := utils.GetRawConfig(cwd)
	if err != nil || persisted.Scripts == nil || persisted.Scripts.Dir != "assets/js" {
		t.Fatalf("defaults not persisted: %+v, %v", persisted, err)
	}
	// An old mtime proves a no-op leaves both files untouched, even on coarse filesystems.
	old := time.Unix(1000000000, 0)
	for _, name := range []string{path, manifestPath} {
		if err := os.Chtimes(name, old, old); err != nil {
			t.Fatal(err)
		}
	}
	_, written, err = UpdateScripts(config)
	if err != nil || written {
		t.Fatalf("second build: written=%v err=%v", written, err)
	}
	for _, name := range []string{path, manifestPath} {
		info, _ := os.Stat(name)
		if !info.ModTime().Equal(old) {
			t.Errorf("rewrote %s", name)
		}
	}
	config.Scripts.Path = "https://cdn.example.com/app/js/"
	_, written, err = UpdateScripts(config)
	if err != nil || !written {
		t.Fatalf("URL change: written=%v err=%v", written, err)
	}
	manifest, _ = os.ReadFile(manifestPath)
	if !strings.Contains(string(manifest), `https://cdn.example.com/app/js/`+filepath.Base(path)) {
		t.Fatalf("manifest URL: %s", manifest)
	}
	write("internal/design/a/a.js", "changed")
	next, _, err := UpdateScripts(config)
	if err != nil {
		t.Fatal(err)
	}
	if next == path {
		t.Fatal("hash did not change")
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("stale bundle retained: %v", err)
	}
	if _, err := os.Stat(filepath.Join(cwd, "assets/js/custom.js")); err != nil {
		t.Fatal(err)
	}
}
