package updaters

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/axadrn/shadcn-templ/v2/cmd/shadcn-templ/utils"
	"github.com/evanw/esbuild/pkg/api"
)

// minifyEngines is Next's default browser target (modern-browserslist-target.js),
// what next build minifies shadcn's components for.
var minifyEngines = []api.Engine{
	{Name: api.EngineChrome, Version: "111"},
	{Name: api.EngineEdge, Version: "111"},
	{Name: api.EngineFirefox, Version: "111"},
	{Name: api.EngineSafari, Version: "16.4"},
}

// UpdateScripts builds the component asset and its Go URL manifest at build
// time. The asset only depends on the scripts of the ui components package
// (aliases.ui), so every app of the module whose ui alias resolves to the
// same directory gets the same bytes: it is written into each app's
// scripts.dir, and the one manifest in the ui components package is correct
// for all of them as long as they serve it under the same scripts.path.
// paths lists the written asset of config's app first, then the other apps'
// assets. Run from the ui workspace itself (a library workspace without
// scripts) it bundles for the apps that use it, none means nothing to do.
// minify writes the asset as next build does; without it the scripts are
// concatenated as they are, like next dev.
func UpdateScripts(config *utils.Config, minify bool) (paths []string, written bool, err error) {
	shared, err := utils.GetSharedConfigs(config)
	if err != nil {
		return nil, false, err
	}
	apps := shared
	if config.Scripts != nil {
		apps = append([]*utils.Config{config}, shared...)
	}
	if len(apps) == 0 {
		return nil, false, nil
	}
	first := apps[0]
	urlPrefix := strings.TrimRight(first.Scripts.Path, "/")
	var dirs []string
	for _, app := range apps {
		if prefix := strings.TrimRight(app.Scripts.Path, "/"); prefix != urlPrefix {
			return nil, false, fmt.Errorf("%s and %s share the ui components package %s but configure different scripts.path (%q and %q); its scripts_bundle.go holds one URL, so use the same scripts.path or separate aliases.ui",
				filepath.Join(first.ResolvedPaths.Cwd, utils.ConfigFileName), filepath.Join(app.ResolvedPaths.Cwd, utils.ConfigFileName), config.UIAlias(), first.Scripts.Path, app.Scripts.Path)
		}
		if !slices.Contains(dirs, app.ResolvedPaths.Scripts) {
			dirs = append(dirs, app.ResolvedPaths.Scripts)
		}
	}

	files, err := filepath.Glob(filepath.Join(config.ResolvedPaths.UI, "*", "*.js"))
	if err != nil {
		return nil, false, err
	}
	// The shared blocks in baseui come first, since components register with
	// them while the bundle loads. Otherwise lexical order, which keeps
	// floating_ui_core before floating_ui_dom.
	sort.SliceStable(files, func(i, j int) bool {
		return isBaseUI(files[i]) && !isBaseUI(files[j])
	})
	// The name hashes the sources, so the watcher's readable asset and the
	// minified one share it and the committed manifest stays put.
	var sources, minified bytes.Buffer
	for _, file := range files {
		if strings.HasSuffix(file, ".min.js") {
			continue
		}
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, false, err
		}
		rel, err := filepath.Rel(config.ResolvedPaths.UI, file)
		if err != nil {
			return nil, false, err
		}
		source := "components/" + filepath.ToSlash(rel)
		fmt.Fprintf(&sources, "// %s\n", source)
		sources.Write(data)
		sources.WriteByte('\n')
		if minify {
			code, err := minifyScript(source, data)
			if err != nil {
				return nil, false, err
			}
			minified.Write(code)
		}
	}
	asset := sources.Bytes()
	if minify {
		asset = minified.Bytes()
	}
	sum := sha256.Sum256(sources.Bytes())
	name := fmt.Sprintf("shadcn-templ-%x.js", sum[:8])
	src := urlPrefix + "/" + name
	manifest, err := format.Source(fmt.Appendf(nil, "// Code generated by shadcn-templ bundle. DO NOT EDIT.\n\npackage %s\n\nconst bundleSrc = %q\n", lastSegment(config.UIAlias()), src))
	if err != nil {
		return nil, false, err
	}
	// Assets first, so the manifest never names a file that is not there yet.
	for _, dir := range dirs {
		path := filepath.Join(dir, name)
		paths = append(paths, path)
		changed, err := writeChanged(path, asset)
		if err != nil {
			return paths, written, err
		}
		written = written || changed
	}
	changed, err := writeChanged(filepath.Join(config.ResolvedPaths.UI, "scripts_bundle.go"), manifest)
	if err != nil {
		return paths, written, err
	}
	written = written || changed
	for _, dir := range dirs {
		stale, err := filepath.Glob(filepath.Join(dir, "shadcn-templ-*.js"))
		if err != nil {
			return paths, written, err
		}
		for _, old := range stale {
			if filepath.Base(old) != name {
				if err := os.Remove(old); err != nil {
					return paths, written, err
				}
				written = true
			}
		}
	}
	if config.ScriptsDefaulted {
		if err := utils.WriteConfig(config.ResolvedPaths.Cwd, &config.RawConfig); err != nil {
			return paths, written, err
		}
		config.ScriptsDefaulted = false
	}
	return paths, written, nil
}

// minifyScript minifies one script on its own, so an error names its file.
// Without a format esbuild keeps top-level names, which the scripts share.
func minifyScript(source string, data []byte) ([]byte, error) {
	result := api.Transform(string(data), api.TransformOptions{
		Sourcefile:        source,
		Loader:            api.LoaderJS,
		Engines:           minifyEngines,
		MinifyWhitespace:  true,
		MinifySyntax:      true,
		MinifyIdentifiers: true,
		LegalComments:     api.LegalCommentsInline,
		Charset:           api.CharsetUTF8,
	})
	if len(result.Errors) > 0 {
		msg := result.Errors[0]
		if loc := msg.Location; loc != nil {
			return nil, fmt.Errorf("%s:%d:%d: %s", loc.File, loc.Line, loc.Column+1, msg.Text)
		}
		return nil, fmt.Errorf("%s: %s", source, msg.Text)
	}
	return result.Code, nil
}

func writeChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return false, err
	}
	// Rename prevents readers from seeing a partially written asset or manifest.
	f, err := os.CreateTemp(filepath.Dir(path), ".bundle-*")
	if err != nil {
		return false, err
	}
	defer os.Remove(f.Name())
	if _, err := f.Write(data); err != nil {
		f.Close()
		return false, err
	}
	if err := f.Chmod(0644); err != nil {
		f.Close()
		return false, err
	}
	if err := f.Close(); err != nil {
		return false, err
	}
	if err := os.Rename(f.Name(), path); err != nil {
		return false, err
	}
	return true, nil
}

func isBaseUI(file string) bool {
	return filepath.Base(filepath.Dir(file)) == "baseui"
}
