package updaters

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/axadrn/shadcn-templ/v2/cmd/shadcn-templ/utils"
)

// UpdateScripts builds the component asset and its Go URL manifest at build time.
func UpdateScripts(config *utils.Config) (path string, written bool, err error) {
	files, err := filepath.Glob(filepath.Join(config.ResolvedPaths.Components, "*", "*.js"))
	if err != nil {
		return "", false, err
	}
	// The shared blocks in baseui come first, since components register with
	// them while the bundle loads. Otherwise lexical order, which keeps
	// floating_ui_core before floating_ui_dom.
	sort.SliceStable(files, func(i, j int) bool {
		return isBaseUI(files[i]) && !isBaseUI(files[j])
	})
	var bundle bytes.Buffer
	for _, file := range files {
		if strings.HasSuffix(file, ".min.js") {
			continue
		}
		data, err := os.ReadFile(file)
		if err != nil {
			return "", false, err
		}
		rel, err := filepath.Rel(config.ResolvedPaths.Components, file)
		if err != nil {
			return "", false, err
		}
		fmt.Fprintf(&bundle, "// components/%s\n", filepath.ToSlash(rel))
		bundle.Write(data)
		bundle.WriteByte('\n')
	}
	sum := sha256.Sum256(bundle.Bytes())
	name := fmt.Sprintf("shadcn-templ-%x.js", sum[:8])
	path = filepath.Join(config.ResolvedPaths.Scripts, name)
	src := strings.TrimRight(config.Scripts.Path, "/") + "/" + name
	manifest, err := format.Source(fmt.Appendf(nil, "// Code generated by shadcn-templ bundle. DO NOT EDIT.\n\npackage %s\n\nconst bundleSrc = %q\n", lastSegment(config.Aliases.Components), src))
	if err != nil {
		return path, false, err
	}
	for _, output := range []struct {
		path string
		data []byte
	}{
		{path, bundle.Bytes()},
		{filepath.Join(config.ResolvedPaths.Components, "scripts_bundle.go"), manifest},
	} {
		changed, err := writeChanged(output.path, output.data)
		if err != nil {
			return path, written, err
		}
		written = written || changed
	}
	stale, err := filepath.Glob(filepath.Join(config.ResolvedPaths.Scripts, "shadcn-templ-*.js"))
	if err != nil {
		return path, written, err
	}
	for _, old := range stale {
		if old != path {
			if err := os.Remove(old); err != nil {
				return path, written, err
			}
			written = true
		}
	}
	if config.ScriptsDefaulted {
		if err := utils.WriteConfig(config.ResolvedPaths.Cwd, &config.RawConfig); err != nil {
			return path, written, err
		}
		config.ScriptsDefaulted = false
	}
	return path, written, nil
}

func writeChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return false, err
	}
	// Rename prevents readers from seeing a partially written asset or manifest.
	f, err := os.CreateTemp(filepath.Dir(path), ".bundle-*")
	if err != nil {
		return false, err
	}
	defer os.Remove(f.Name())
	if _, err := f.Write(data); err != nil {
		f.Close()
		return false, err
	}
	if err := f.Chmod(0644); err != nil {
		f.Close()
		return false, err
	}
	if err := f.Close(); err != nil {
		return false, err
	}
	if err := os.Rename(f.Name(), path); err != nil {
		return false, err
	}
	return true, nil
}

func isBaseUI(file string) bool {
	return filepath.Base(filepath.Dir(file)) == "baseui"
}
